@echo off
echo Starting HiddenGem API with GPU support...
echo Using Python from hiddengem_gpu environment...
cd "D:\Program Files (x86)\CodeRepos\HiddenGem\backend"
C:\ProgramData\miniconda3\envs\hiddengem_gpu\python.exe -m uvicorn api.main:app --reload --host 192.168.24.2 --port 8000
