"""
SQLAlchemy database models for HiddenGem trading system.
"""

from datetime import datetime
from decimal import Decimal
from enum import Enum as PyEnum
from typing import Optional

from sqlalchemy import (
    Boolean, Column, DateTime, Enum, Float, ForeignKey,
    Integer, JSON, Numeric, String, Text, Index, UniqueConstraint
)
from sqlalchemy.orm import relationship

from config.database import Base


# Enums
class TradingBoard(str, PyEnum):
    """A-Share trading boards."""
    MAIN = "main"           # Main board (主板)
    CHINEXT = "chinext"     # ChiNext/Growth Enterprise Board (创业板) - 300xxx
    STAR = "star"           # STAR Market (科创板) - 688xxx


class OrderSide(str, PyEnum):
    """Order side."""
    BUY = "buy"
    SELL = "sell"


class OrderType(str, PyEnum):
    """Order type."""
    MARKET = "market"
    LIMIT = "limit"
    STOP_LOSS = "stop_loss"
    STOP_PROFIT = "stop_profit"


class OrderStatus(str, PyEnum):
    """Order status."""
    PENDING = "pending"
    SUBMITTED = "submitted"
    PARTIAL_FILLED = "partial_filled"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"
    EXPIRED = "expired"


class SignalDirection(str, PyEnum):
    """Trading signal direction."""
    LONG = "long"    # Buy signal
    SHORT = "short"  # Sell signal
    HOLD = "hold"    # Hold position
    CLOSE = "close"  # Close position


class RiskLevel(str, PyEnum):
    """Risk level."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


# Models
class MarketData(Base):
    """
    Time-series market data (OHLCV).
    This should be converted to a TimescaleDB hypertable.
    """
    __tablename__ = "market_data"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False, index=True)

    # OHLCV data
    open = Column(Numeric(10, 2), nullable=False)
    high = Column(Numeric(10, 2), nullable=False)
    low = Column(Numeric(10, 2), nullable=False)
    close = Column(Numeric(10, 2), nullable=False)
    volume = Column(Integer, nullable=False)  # Volume in shares
    amount = Column(Numeric(20, 2), nullable=False)  # Trading amount in RMB

    # Additional fields
    turnover_rate = Column(Float, nullable=True)  # Turnover rate %
    pe_ratio = Column(Float, nullable=True)
    pb_ratio = Column(Float, nullable=True)

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        UniqueConstraint('symbol', 'timestamp', name='uq_market_data_symbol_timestamp'),
        Index('idx_market_data_symbol_timestamp', 'symbol', 'timestamp'),
    )


class Signal(Base):
    """Trading signals generated by agents."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, index=True)
    direction = Column(Enum(SignalDirection), nullable=False)
    strength = Column(Float, nullable=False)  # 0.0 to 1.0
    timestamp = Column(DateTime, nullable=False, index=True, default=datetime.utcnow)

    # Signal source
    agent_name = Column(String(50), nullable=False)
    strategy_name = Column(String(50), nullable=True)

    # Target prices
    entry_price = Column(Numeric(10, 2), nullable=True)
    target_price = Column(Numeric(10, 2), nullable=True)
    stop_loss_price = Column(Numeric(10, 2), nullable=True)

    # Position sizing
    suggested_position_size = Column(Float, nullable=True)  # Percentage of portfolio

    # Analysis
    reasoning = Column(Text, nullable=True)  # Why this signal was generated
    signal_metadata = Column(JSON, nullable=True)  # Additional signal data

    # Execution tracking
    is_executed = Column(Boolean, default=False, nullable=False)
    order_id = Column(Integer, ForeignKey('orders.id'), nullable=True)

    # Relationships
    order = relationship("Order", back_populates="signal")

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        Index('idx_signals_symbol_timestamp', 'symbol', 'timestamp'),
        Index('idx_signals_agent_timestamp', 'agent_name', 'timestamp'),
    )


class Order(Base):
    """Order records."""
    __tablename__ = "orders"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, index=True)
    side = Column(Enum(OrderSide), nullable=False)
    order_type = Column(Enum(OrderType), nullable=False)
    status = Column(Enum(OrderStatus), nullable=False, default=OrderStatus.PENDING)

    # Quantities and prices
    quantity = Column(Integer, nullable=False)  # Number of shares
    price = Column(Numeric(10, 2), nullable=True)  # For limit orders
    filled_quantity = Column(Integer, default=0, nullable=False)
    avg_filled_price = Column(Numeric(10, 2), nullable=True)

    # Trading board
    board = Column(Enum(TradingBoard), nullable=False)

    # Commission and fees
    commission = Column(Numeric(10, 2), default=0, nullable=False)
    tax = Column(Numeric(10, 2), default=0, nullable=False)  # Stamp duty for A-shares

    # External IDs
    broker_order_id = Column(String(100), nullable=True, unique=True)

    # Timestamps
    submitted_at = Column(DateTime, nullable=True)
    filled_at = Column(DateTime, nullable=True)
    cancelled_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Strategy and signal tracking
    strategy_name = Column(String(50), nullable=True)
    signal_id = Column(Integer, nullable=True)

    # Error tracking
    error_message = Column(Text, nullable=True)

    # Relationships
    signal = relationship("Signal", back_populates="order")
    position_updates = relationship("Position", back_populates="last_order")

    __table_args__ = (
        Index('idx_orders_symbol_status', 'symbol', 'status'),
        Index('idx_orders_created_at', 'created_at'),
    )


class Position(Base):
    """Current portfolio positions."""
    __tablename__ = "positions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, unique=True, index=True)

    # Position details
    quantity = Column(Integer, nullable=False)  # Current holdings
    avg_cost = Column(Numeric(10, 2), nullable=False)  # Average cost price
    current_price = Column(Numeric(10, 2), nullable=True)  # Last known price

    # Trading board
    board = Column(Enum(TradingBoard), nullable=False)

    # P&L
    unrealized_pnl = Column(Numeric(20, 2), nullable=True)
    unrealized_pnl_pct = Column(Float, nullable=True)
    realized_pnl = Column(Numeric(20, 2), default=0, nullable=False)

    # Risk management
    stop_loss_price = Column(Numeric(10, 2), nullable=True)
    take_profit_price = Column(Numeric(10, 2), nullable=True)

    # Position metadata
    entry_date = Column(DateTime, nullable=False)
    last_order_id = Column(Integer, ForeignKey('orders.id'), nullable=True)
    strategy_name = Column(String(50), nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    last_order = relationship("Order", back_populates="position_updates")


class PortfolioSnapshot(Base):
    """Portfolio state snapshots over time."""
    __tablename__ = "portfolio_snapshots"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, nullable=False, index=True, default=datetime.utcnow)

    # Portfolio value
    total_value = Column(Numeric(20, 2), nullable=False)
    cash = Column(Numeric(20, 2), nullable=False)
    positions_value = Column(Numeric(20, 2), nullable=False)

    # Performance metrics
    total_pnl = Column(Numeric(20, 2), nullable=False)
    total_pnl_pct = Column(Float, nullable=False)
    daily_pnl = Column(Numeric(20, 2), nullable=True)
    daily_pnl_pct = Column(Float, nullable=True)

    # Risk metrics
    sharpe_ratio = Column(Float, nullable=True)
    max_drawdown = Column(Float, nullable=True)
    volatility = Column(Float, nullable=True)

    # Position count
    num_positions = Column(Integer, default=0, nullable=False)

    # Detailed snapshot
    positions_detail = Column(JSON, nullable=True)  # List of position details
    sector_allocation = Column(JSON, nullable=True)  # Sector exposure breakdown

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        Index('idx_portfolio_snapshots_timestamp', 'timestamp'),
    )


class AgentAnalysis(Base):
    """Agent analysis results."""
    __tablename__ = "agent_analyses"

    id = Column(Integer, primary_key=True, autoincrement=True)
    agent_name = Column(String(50), nullable=False, index=True)
    symbol = Column(String(20), nullable=True, index=True)  # Null for market-wide analysis
    timestamp = Column(DateTime, nullable=False, index=True, default=datetime.utcnow)

    # Analysis results
    score = Column(Float, nullable=True)  # Agent-specific score
    direction = Column(Enum(SignalDirection), nullable=True)
    confidence = Column(Float, nullable=True)  # 0.0 to 1.0

    # Detailed analysis
    analysis = Column(JSON, nullable=False)  # Agent-specific analysis data
    reasoning = Column(Text, nullable=True)

    # Execution time
    execution_time_ms = Column(Integer, nullable=True)

    # Error tracking
    is_error = Column(Boolean, default=False, nullable=False)
    error_message = Column(Text, nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        Index('idx_agent_analyses_agent_timestamp', 'agent_name', 'timestamp'),
        Index('idx_agent_analyses_symbol_timestamp', 'symbol', 'timestamp'),
    )


class RiskEvent(Base):
    """Risk alert events."""
    __tablename__ = "risk_events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=True, index=True)  # Null for portfolio-level risk
    risk_type = Column(String(50), nullable=False, index=True)
    risk_level = Column(Enum(RiskLevel), nullable=False)
    timestamp = Column(DateTime, nullable=False, index=True, default=datetime.utcnow)

    # Risk details
    description = Column(Text, nullable=False)
    metrics = Column(JSON, nullable=True)  # Risk metrics that triggered the alert

    # Resolution
    is_resolved = Column(Boolean, default=False, nullable=False)
    resolved_at = Column(DateTime, nullable=True)
    resolution_action = Column(Text, nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    __table_args__ = (
        Index('idx_risk_events_type_level', 'risk_type', 'risk_level'),
        Index('idx_risk_events_timestamp', 'timestamp'),
    )


class StockInfo(Base):
    """Stock basic information and A-share specific data."""
    __tablename__ = "stock_info"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, unique=True, index=True)
    name = Column(String(100), nullable=False)
    board = Column(Enum(TradingBoard), nullable=False)

    # Industry classification
    industry = Column(String(100), nullable=True)
    sector = Column(String(100), nullable=True)

    # A-share specific risks
    pledge_ratio = Column(Float, nullable=True)  # Share pledge ratio
    restricted_shares_ratio = Column(Float, nullable=True)
    next_unlock_date = Column(DateTime, nullable=True)
    next_unlock_volume = Column(Integer, nullable=True)
    goodwill = Column(Numeric(20, 2), nullable=True)  # Goodwill in RMB
    total_assets = Column(Numeric(20, 2), nullable=True)  # Total assets in RMB

    # Fundamental data
    market_cap = Column(Numeric(20, 2), nullable=True)
    pe_ratio = Column(Float, nullable=True)
    pb_ratio = Column(Float, nullable=True)
    roe = Column(Float, nullable=True)
    debt_to_equity = Column(Float, nullable=True)

    # Trading info
    is_tradable = Column(Boolean, default=True, nullable=False)
    is_st = Column(Boolean, default=False, nullable=False)  # Special Treatment status
    listing_date = Column(DateTime, nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    @property
    def goodwill_ratio(self) -> Optional[float]:
        """Calculate goodwill as percentage of total assets."""
        if self.goodwill and self.total_assets and self.total_assets > 0:
            return float(self.goodwill / self.total_assets)
        return None
